### ISSUE TITLE
请问有无 RSS 订阅地址

### ISSUE THREAD

**Issue by HaoshuaiXu** [eryajf/Obsidian-Plugin-Weekly#1]
挺好的，想关注一下，平时类似的周刊形式的内容会用一些 RSS 阅读器来订阅，不知可否提供

**Comment by eryajf** [comment]
我会寻找rss的方式，随后空了配置上来

**Comment by eryajf** [comment]
> 挺好的，想关注一下，平时类似的周刊形式的内容会用一些 RSS 阅读器来订阅，不知可否提供

现在，你可以通过此链接进行订阅：http://ob-plugin.eryajf.net/feed.xml

**Comment by HaoshuaiXu** [comment]
非常 nice 呀，感谢！
